FROM amd64/ubuntu:14.04@sha256:bd0223687054d0f8884fc9e872392c6385a3195d612400495962e270b572ed06

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Ubuntu" \
  org.label-schema.version="14.04" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENV CRON_ENABLED false
ENV TERM xterm
ENV DEBIAN_FRONTEND noninteractive

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y ca-certificates bash bash-completion ncurses-base vim curl procps apt-transport-https cron && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay ./overlay-amd64 /

RUN apt-get update && \
  apt-get install -y build-essential && \
  curl -sSL -o- https://github.com/skarnet/skalibs/archive/v2.7.0.0.tar.gz | tar -xvz -C /tmp && \
  cd /tmp/skalibs-2.7.0.0 && \
  ./configure && \
  make && \
  make install && \
  rm -rf /tmp/skalibs-2.7.0.0 && \
  curl -sSL -o- https://github.com/skarnet/execline/archive/v2.5.0.1.tar.gz | tar -xvz -C /tmp && \
  cd /tmp/execline-2.5.0.1 && \
  ./configure && \
  make && \
  make install && \
  rm -rf /tmp/execline-2.5.0.1 && \
  curl -sSL -o- https://github.com/skarnet/s6/archive/v2.7.2.2.tar.gz | tar -xvz -C /tmp && \
  cd /tmp/s6-2.7.2.2 && \
  ./configure && \
  make && \
  make install && \
  rm -rf /tmp/s6-2.7.2.2 && \
  apt-get purge -y build-essential && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
