FROM ubuntu:22.04@sha256:1aa979d85661c488ce030ac292876cf6ed04535d3a237e49f61542d8e5de5ae0 AS build

ENV TERM=xterm
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
  apt-get install -y wget ca-certificates

# renovate: datasource=github-releases depName=thegeeklab/wait-for
ENV WAITFOR_VERSION=0.4.3

RUN wget --no-check-certificate -O /tmp/wait-for-it https://github.com/thegeeklab/wait-for/releases/download/v${WAITFOR_VERSION}/wait-for && \
  chmod +x /tmp/wait-for-it && \
  /tmp/wait-for-it --help >/dev/null

# renovate: datasource=github-releases depName=hairyhenderson/gomplate
ENV GOMPLATE_VERSION=4.3.3

RUN wget --no-check-certificate -O /tmp/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_linux-amd64 && \
  chmod +x /tmp/gomplate && \
  /tmp/gomplate --help >/dev/null

# renovate: datasource=github-releases depName=krallin/tini
ENV TINI_VERSION=0.19.0

RUN wget --no-check-certificate -O /tmp/tini https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-amd64 && \
  chmod +x /tmp/tini && \
  /tmp/tini --version >/dev/null

# renovate: datasource=github-releases depName=tianon/gosu
ENV GOSU_VERSION=1.13

RUN wget --no-check-certificate -O /tmp/su-exec https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64 && \
  chmod +x /tmp/su-exec && \
  /tmp/su-exec --help >/dev/null

FROM ubuntu:22.04@sha256:1aa979d85661c488ce030ac292876cf6ed04535d3a237e49f61542d8e5de5ae0

ENV CRON_ENABLED=false
ENV TERM=xterm
ENV DEBIAN_FRONTEND=noninteractive

ENTRYPOINT ["/usr/sbin/tini", "--", "/usr/bin/entrypoint"]
CMD ["bash"]

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y ca-certificates bash bash-completion ncurses-base vim curl procps apt-transport-https cron execline s6 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay /

COPY --from=build /tmp/wait-for-it /usr/bin/
COPY --from=build /tmp/gomplate /usr/bin/
COPY --from=build /tmp/su-exec /usr/sbin/
COPY --from=build /tmp/tini /usr/sbin/
