FROM amd64/ubuntu:20.10@sha256:6166dad89a1e4448f25a59ddd763bdc2ce95f784edc8bd5744562529134ce652

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Ubuntu" \
  org.opencontainers.image.vendor="Thomas Boerger"

ENV CRON_ENABLED false
ENV TERM xterm
ENV DEBIAN_FRONTEND noninteractive

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/entrypoint"]
CMD ["bash"]

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y ca-certificates bash bash-completion ncurses-base vim curl procps apt-transport-https cron execline s6 && \
  curl -sSLo /usr/bin/wait-for-it https://raw.githubusercontent.com/thegeeklab/wait-for/d17c23172a39d7555f184d916881aeae6d446a22/wait-for && \
  chmod +x /usr/bin/wait-for-it && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay ./overlay-amd64 /
