FROM amd64/ubuntu:19.10@sha256:7ce552ad1c3e94a5c3d2bb24c07000c34a4bb43fd9b379652b2c80593a018e80

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Ubuntu" \
  org.label-schema.version="19.10" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENV CRON_ENABLED false
ENV TERM xterm
ENV DEBIAN_FRONTEND noninteractive

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y ca-certificates bash bash-completion ncurses-base vim curl procps apt-transport-https cron execline s6 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay ./overlay-amd64 /
