FROM arm64v8/ubuntu:18.04@sha256:41655dcc90bca6c0063eba1f24c7c9d151c2da379c4e56b9850dc3e3a27abde9 AS build

ENV TERM xterm
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && \
  apt-get install -y wget ca-certificates

# renovate: datasource=github-releases depName=thegeeklab/wait-for
ENV WAITFOR_VERSION=0.2.0

RUN wget --no-check-certificate -O /tmp/wait-for-it https://github.com/thegeeklab/wait-for/releases/download/v${WAITFOR_VERSION}/wait-for && \
  chmod +x /tmp/wait-for-it

# renovate: datasource=github-releases depName=hairyhenderson/gomplate
ENV GOMPLATE_VERSION=3.9.0

RUN wget --no-check-certificate -O /tmp/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_linux-arm64 && \
  chmod +x /tmp/gomplate

# renovate: datasource=github-releases depName=krallin/tini
ENV TINI_VERSION=0.19.0

RUN wget --no-check-certificate -O /tmp/tini https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-arm64 && \
  chmod +x /tmp/tini

# renovate: datasource=github-releases depName=tianon/gosu
ENV GOSU_VERSION=1.13

RUN wget --no-check-certificate -O /tmp/su-exec https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-arm64 && \
  chmod +x /tmp/su-exec

FROM arm64v8/ubuntu:18.04@sha256:41655dcc90bca6c0063eba1f24c7c9d151c2da379c4e56b9850dc3e3a27abde9

ENV CRON_ENABLED false
ENV TERM xterm
ENV DEBIAN_FRONTEND noninteractive

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/entrypoint"]
CMD ["bash"]

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y ca-certificates bash bash-completion ncurses-base vim curl procps apt-transport-https cron && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay /

COPY --from=build /tmp/wait-for-it /usr/bin/
COPY --from=build /tmp/gomplate /usr/bin/
COPY --from=build /tmp/su-exec /usr/sbin/
COPY --from=build /tmp/tini /usr/sbin/

# renovate: datasource=github-tags depName=skarnet/skalibs
ENV SKALIBS_VERSION=2.7.0.0

# renovate: datasource=github-tags depName=skarnet/execline
ENV EXECLINE_VERSION=2.5.0.1

# renovate: datasource=github-tags depName=skarnet/s6
ENV S6_VERSION=2.7.2.2

RUN apt-get update && \
  apt-get install -y build-essential && \
  curl -sSL -o- https://github.com/skarnet/skalibs/archive/v${SKALIBS_VERSION}.tar.gz | tar -xvz -C /tmp && \
  cd /tmp/skalibs-${SKALIBS_VERSION} && \
  ./configure && \
  make && \
  make install && \
  rm -rf /tmp/skalibs-${SKALIBS_VERSION} && \
  curl -sSL -o- https://github.com/skarnet/execline/archive/v${EXECLINE_VERSION}.tar.gz | tar -xvz -C /tmp && \
  cd /tmp/execline-${EXECLINE_VERSION} && \
  ./configure && \
  make && \
  make install && \
  rm -rf /tmp/execline-${EXECLINE_VERSION} && \
  curl -sSL -o- https://github.com/skarnet/s6/archive/v${S6_VERSION}.tar.gz | tar -xvz -C /tmp && \
  cd /tmp/s6-${S6_VERSION} && \
  ./configure && \
  make && \
  make install && \
  rm -rf /tmp/s6-${S6_VERSION} && \
  apt-get purge -y build-essential && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
