FROM amd64/ubuntu:18.04@sha256:c404618e908391e50953e1ead94fe05dbbddbf532bd5c89b935ef34a9ca130d3

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Ubuntu" \
  org.opencontainers.image.vendor="Thomas Boerger"

ENV CRON_ENABLED false
ENV TERM xterm
ENV DEBIAN_FRONTEND noninteractive

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/entrypoint"]
CMD ["bash"]

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y ca-certificates bash bash-completion ncurses-base vim curl procps apt-transport-https cron && \
  curl -sSLo /usr/bin/wait-for-it https://raw.githubusercontent.com/thegeeklab/wait-for/d17c23172a39d7555f184d916881aeae6d446a22/wait-for && \
  chmod +x /usr/bin/wait-for-it && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay ./overlay-amd64 /

RUN apt-get update && \
  apt-get install -y build-essential && \
  curl -sSL -o- https://github.com/skarnet/skalibs/archive/v2.7.0.0.tar.gz | tar -xvz -C /tmp && \
  cd /tmp/skalibs-2.7.0.0 && \
  ./configure && \
  make && \
  make install && \
  rm -rf /tmp/skalibs-2.7.0.0 && \
  curl -sSL -o- https://github.com/skarnet/execline/archive/v2.5.0.1.tar.gz | tar -xvz -C /tmp && \
  cd /tmp/execline-2.5.0.1 && \
  ./configure && \
  make && \
  make install && \
  rm -rf /tmp/execline-2.5.0.1 && \
  curl -sSL -o- https://github.com/skarnet/s6/archive/v2.7.2.2.tar.gz | tar -xvz -C /tmp && \
  cd /tmp/s6-2.7.2.2 && \
  ./configure && \
  make && \
  make install && \
  rm -rf /tmp/s6-2.7.2.2 && \
  apt-get purge -y build-essential && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
