---
name: latest

"on":
  push:
    branches:
      - master
    paths:
      - latest/*
      - .github/workflows/docker.yml
  pull_request:
    branches:
      - master
    paths:
      - latest/*
      - .github/workflows/docker.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            webhippie/ubuntu
            ghcr.io/webhippie/ubuntu
            quay.io/webhippie/ubuntu
          labels: |
            org.opencontainers.image.vendor=Webhippie
            maintainer=Thomas Boerger <thomas@webhippie.de>

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Quay login
        id: login1
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Ghcr login
        id: login2
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Hub login
        id: login3
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build amd64
        id: amd64
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: latest/
          file: latest/Dockerfile.amd64
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/ubuntu:latest-amd64
            ghcr.io/webhippie/ubuntu:latest-amd64
            quay.io/webhippie/ubuntu:latest-amd64

      - name: Build arm64
        id: arm64
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: latest/
          file: latest/Dockerfile.arm64
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/ubuntu:latest-arm64
            ghcr.io/webhippie/ubuntu:latest-arm64
            quay.io/webhippie/ubuntu:latest-arm64

      - name: Build arm
        id: arm
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: latest/
          file: latest/Dockerfile.arm
          platforms: linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/ubuntu:latest-arm
            ghcr.io/webhippie/ubuntu:latest-arm
            quay.io/webhippie/ubuntu:latest-arm

      - name: Hub manifest
        id: manifest1
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          template: webhippie/ubuntu:latest-ARCH
          target: webhippie/ubuntu:latest
          ignore_missing: true

      - name: Ghcr manifest
        id: manifest2
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          template: ghcr.io/webhippie/ubuntu:latest-ARCH
          target: ghcr.io/webhippie/ubuntu:latest
          ignore_missing: true

      - name: Quay manifest
        id: manifest3
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          template: quay.io/webhippie/ubuntu:latest-ARCH
          target: quay.io/webhippie/ubuntu:latest
          ignore_missing: true

...
