name: readme

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/readme.yml

jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2

      - name: Push readme
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # renovate: tag=v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: webhippie/ubuntu
          provider: dockerhub
          short_description: Docker images for Alpine
          readme_file: README.md

  quayio:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2

      - name: Push readme
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # renovate: tag=v1
        env:
          DOCKER_APIKEY: ${{ secrets.QUAY_APIKEY }}
        with:
          destination_container_repo: quay.io/webhippie/ubuntu
          provider: quay
          readme_file: README.md
